### ISSUE TITLE
Unable to transfer DLPT tokens

### ISSUE THREAD

**Issue by pvsairam** [vana-com/vana-dlp-chatgpt#60]
I am trying to transfer DLPT (Contract address - 0x154bA8E1C1Fa293cF0358040209fc28982378d4d) tokens to another wallet and it is getting failed due to below error:

![image](https://github.com/user-attachments/assets/87a9d230-e73d-4d26-bd27-544588cc849d)

![image](https://github.com/user-attachments/assets/351afe29-51f1-4195-b870-9e622e959a03)

Error: An internal error was received.

Details: Internal JSON-RPC error.
Version: viem@2.10.9

**Comment by volod-vana** [comment]
This is happening because you need to mint those tokens and approve before transfer. See this snippet from the deployment script for better understanding.

```
await dlpt.connect(deployer).mint(deployer.address, parseEther('10000000'));
...
await dlpt.connect(deployer).approve(dlp, parseEther('3000000'));
await dlp.connect(deployer).addRewardForValidators(parseEther('2000000'));
await dlp.connect(deployer).addRewardsForContributors(parseEther('1000000'));
await dlpt.connect(deployer).transfer(ownerAddress, parseEther('7000000'));
```

Other way arround this is that you might transfer those tokens from the deployer address, e.g. `0xF9810b951d45D19754435D8e44b7761aA1635D72`

**Comment by pvsairam** [comment]
I am trying to transfer tokens using deployer address but it is not getting through:

![image](https://github.com/user-attachments/assets/db9c092c-685c-42fa-8535-2573cfcfa5bb)

Error - Internal JSON-RPC error.

![image](https://github.com/user-attachments/assets/e122e97d-2469-4ff4-ae5e-07f74348f1c5)

**Comment by pvsairam** [comment]
I have re-added the network, and the issue is resolved!
