### ISSUE TITLE
Not found web Page and no tab "Write proxy"

### ISSUE THREAD

**Issue by netlogs** [vana-com/vana-dlp-chatgpt#65]
In docs [running_on_testnet.md](https://github.com/vana-com/vana-dlp-chatgpt/blob/main/docs/running_on_testnet.md#running-a-validator-on-an-existing-dlp:~:text=Visit%20https%3A//satori.vanascan.io/address/)

Not found this web page on browser：
![image](https://github.com/user-attachments/assets/261a1848-9b4b-4de0-939b-e8e615090ab6)

and not found **the tab "Write proxy"**

I hope I was wrong

**Comment by Kahtaf** [comment]
Apologies if the docs were unclear, you'll need to append the address of the contract you just deployed. 

ie: after running `npx hardhat deploy --network satori --tags DLPDeploy`, you'll see the address where it's deployed, ex: `0xabcd1234`. 

Then you can see it in the block explorer by going to https://satori.vanascan.io/address/0xabcd1234.

**Comment by netlogs** [comment]
I can access it through https://satori.vanascan.io/address/0xabcd1234

The issue I am concerned about is there is no tab: **"Write proxy"**

**Comment by netlogs** [comment]
sry, my bad. I find the tab "Write proxy" now. but!!
maybe we should update docs, like this:
...
8. Configure the DLP contract:
- Visit https://satori.vanascan.io/address/$DataLiquidityPool
- go to tab "Contract"
- then go to tab "Write proxy"

...
